[build]
builder = "nixpacks"
buildCommand = "echo building!"

[deploy]
startCommand = "mvn spring-boot:run"
healthcheckPath = "/src/main/java/com.example.cowinibooti/CowiniBootiApplication"
healthcheckTimeout = 100
restartPolicyType = "never"
